services:
  payment-caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: payment-caddy
    ports:
      - 9001:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  
  static:
    image: caddy:latest
    container_name: static
    volumes:
      - ./static/index.html:/usr/share/caddy/index.html
      - ./static/Caddyfile:/etc/caddy/Caddyfile
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "--host"]
    container_name: app
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/static:/usr/src/app/static

  service:
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - SERVICE_NAME=service
    volumes:
      - ./service/src:/app/src
    container_name: service
    # scale: 3
    env_file:
      - ./.env

  socketio:
    build:
      context: ./socketio
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - SERVICE_NAME=socketio
    volumes:
      - ./socketio/src:/app/src
    container_name: socketio
    ports:
      - "4242:8000"
    # scale: 3
    env_file:
      - ./.env

  strapi:
    container_name: strapi
    build: ./strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/db/data.db:/tmp/data.db
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      # - ./strapi/.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"



networks:
  default:
    name: traefik
    external: true

