# Use an official Node.js runtime as a parent image
FROM node:21-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml (or just `package.json` if no lock file)
COPY package.json ./
COPY pnpm-lock.yaml* ./

# Install dependencies using pnpm
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code

# Expose the port the app runs on
EXPOSE 5173
COPY . .

